## Nested if

In [5]:
x = int(input("Enter a number: "))
if x>10:
    print("x is greater than 10")
    if x>20:
        print("x is also greater than 20")
    else:
        print("But not above 20")

Enter a number:  12


x is greater than 10
But not above 20


In [33]:
x = int(input("Enter your marks :"))
if 0<=x<=40:
    print("Grade: E \nPull up your socks")
elif (40<x<=50):
        print("Grade: D \nYou can do it!")
elif (50<x<=60):
        print("Grade: C \nYou can do it")
elif (60<x<=70):
        print("Grade:B \nAlmost there!Keep going!")
elif (70<x<=100):
        print("Grade: A \nExcellent!Keep up")
else:
    print("Invalid!Please Try again")        
                

Enter your marks : 88


Grade: A 
Excellent!Keep up


## While loop

In [36]:
n =int(input("Enter a number: "))
i=1
while i<n:
    print (i)
    print("I am inside the loop")
    i+=1
    print("Done!!")

Enter a number:  4


1
I am inside the loop
Done!!
2
I am inside the loop
Done!!
3
I am inside the loop
Done!!


In [42]:
#Check if a number is even
v=int(input("Enter a number: "))
print (v%2)

Enter a number:  100


0


## While loop that returns only even numbers

In [52]:
s=int(input("Enter a number: "))
r=0
while r<s:
    if r%2 == 0:
        print (r)
    else:
        pass
    r+=1
print("Done!")

Enter a number:  7


0
2
4
6
Done!


## Break and continue in loops

In [62]:
n=int(input("Enter a number:"))
i=3
while i<n:
    if i%2 == 0:
        print(i)
        break #breaks the loop after an even number is found
    i+=1
    continue #skips to the next iteration
    print("I am forgotten")
print("Done!")

Enter a number: 7


4
Done!


## For Loop

In [70]:
L = []
for i in range (5):
    print(i)
    L.append(i**2) #list will contain elements that are squares of elements in the i range
print("Done")

0
1
2
3
4
Done


In [71]:
L

[0, 1, 4, 9, 16]

In [76]:
S = {"Violet","WM",22,2002}
for x in S:
    print(x)
else:
    print("Done")

2002
WM
Violet
22
Done


In [77]:
S

{2002, 22, 'Violet', 'WM'}

In [88]:
D = {"Name":"Violet","Initials":"WM","Age":22,"YOB":2002}
for x in D:
    result = x + ":" + str(D[x])
    print(result)
    

Name:Violet
Initials:WM
Age:22
YOB:2002


## Functions

In [90]:
def printSuccessMessage():
    """This is a docstring; it describes what the work of the function is"""
    print("Successful")

In [94]:
printSuccessMessage()

Successful


In [95]:
printSuccessMessage?

Signature: printSuccessMessage()
Docstring: This is a docstring; it describes what the work of the function is
File:      c:\users\violet\appdata\local\temp\ipykernel_12900\3426253607.py
Type:      function

In [96]:
help(printSuccessMessage)

Help on function printSuccessMessage in module __main__:

printSuccessMessage()
    This is a docstring; it describes what the work of the function is



In [102]:
def printMe(Violet):
    print(Violet)

In [103]:
printMe("Wamzzz")

Wamzzz


In [104]:
def add(x,y):
    print(x+y)

In [105]:
add(4,5)

9


In [108]:
def mul(a,b):
    return a*b

In [109]:
c = mul(4,5)

In [110]:
c

20

In [114]:
def AddAll(*args):
    s = 0
    for x in args:
        s += x
    return s

In [116]:
AddAll(3,4,5,6,7)

25

In [117]:
def f(**c):
    for x in c:
        print(x,c[x])

In [118]:
f(a = "A",b = "B",c = "C")

a A
b B
c C


In [119]:
def m(m1,m2,m3):
    print(m1,m2,m3)

In [120]:
m(m3="B",m1 ="v",m2="N")

v N B


## Modules

In [139]:
# Should work if the file is saved as myfuncs.py

import sys
sys.path.append('C:/Users/VIOLET/Downloads/')
import myfuncs as mf

In [140]:
mf.printList([1,3,5,7])

1
3
5
7


In [141]:
mf.printList?

Signature: mf.printList(L=[])
Docstring:
This function prints the list elements
The input is a list and default is an empty list
File:      c:\users\violet\downloads\ml\myfuncs.py
Type:      function

In [142]:
mf.printMe('Helloo')

Helloo


In [143]:
mf.printMe()

No message was supplied


## Numpy

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.24.3


In [3]:
A = np.array([1,3,5,7])

In [4]:
A

array([1, 3, 5, 7])

In [5]:
A.dtype

dtype('int32')

In [6]:
A[0] = 9.5

In [7]:
A[0]

9

In [8]:
A.ndim

1

In [9]:
B = np.array([[1,2,3,4],[5,6,7,8]])

In [10]:
B.ndim

2

In [11]:
C = np.array([[[1,2,3.2],[4.5,5,6],[7,8,9.2]],[[10,20,30],[12,24,36],[11,22,33]]])

In [12]:
C

array([[[ 1. ,  2. ,  3.2],
        [ 4.5,  5. ,  6. ],
        [ 7. ,  8. ,  9.2]],

       [[10. , 20. , 30. ],
        [12. , 24. , 36. ],
        [11. , 22. , 33. ]]])

In [13]:
C.ndim

3

In [14]:
C.shape

(2, 3, 3)

In [15]:
C.shape[2]

3

In [16]:
print(C[1])

[[10. 20. 30.]
 [12. 24. 36.]
 [11. 22. 33.]]


In [17]:
C[1,2,2]

33.0

In [18]:
V=np.arange(10)

In [19]:
V

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
V[-2]

8

In [21]:
V[2:6] #prints elements from index 2 to 6,except 6

array([2, 3, 4, 5])

In [22]:
V[::-1] #reverses the elements in the array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [23]:
V[::2] #picks every second element

array([0, 2, 4, 6, 8])

In [24]:
V[2:] #prints elements from index 2 till the last,including the last element

array([2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
V[:5] #prints all elements upto the element in index 5,except element in index 5

array([0, 1, 2, 3, 4])

In [26]:
W=np.random.permutation(np.arange(10))

In [27]:
W

array([7, 1, 3, 2, 6, 9, 0, 4, 8, 5])

In [31]:
W[[2,4,9]] #Array indexing

array([3, 6, 5])

In [32]:
W[[True,True,False,True,False,False,True,False,True,False]]

array([7, 1, 2, 0, 8])

In [33]:
W[W<4]

array([1, 3, 2, 0])

In [35]:
W.any()

True

In [36]:
W.all()

False

In [39]:
Z=np.random.rand(1000000)
%timeit np.sum(Z)

1.29 ms ± 73.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [40]:
%timeit Z.sum()

1.34 ms ± 96.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [41]:
%timeit sum(Z)

103 ms ± 3.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [42]:
%%timeit
s=0
for x in Z:
    s+=x

128 ms ± 6.16 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
