#LEARNING NUMPY

In [1]:
import numpy as np

In [2]:
np.array ([1,3,5,7])

array([1, 3, 5, 7])

In [3]:
A = np.mat([[1,2],[3,5]])

In [4]:
A + A

matrix([[ 2,  4],
        [ 6, 10]])

In [5]:
A * A

matrix([[ 7, 12],
        [18, 31]])

# Finding the determinant

In [6]:
np.linalg.det(A)

-1.0000000000000004

# Transposition -row becomes column

In [7]:
np.matrix.transpose(A)

matrix([[1, 3],
        [2, 5]])

In [9]:
A = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
A*2

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [13]:
np.linalg.det(A)

-9.51619735392994e-16

In [14]:
np.matrix.transpose(A)

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [15]:
A**2

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

# Getting dimensions of an array

In [30]:
b = np.array([[1,2],[2,3],[1,3]])

In [31]:
print(b)

[[1 2]
 [2 3]
 [1 3]]


In [32]:
b.ndim

2

In [35]:
a = np.array([1,2,3])

In [38]:
a.ndim

1

In [39]:
print (a)

[1 2 3]


In [43]:
array = np.array([[1,2],[4,6],[7,9]])

In [44]:
print (array)

[[1 2]
 [4 6]
 [7 9]]


In [46]:
array.ndim

2

In [47]:
# Creating a 3x3x3 array
array_3d = np.array([[[1, 2, 3], 
                      [4, 5, 6], 
                      [7, 8, 9]], 

                     [[10, 11, 12], 
                      [13, 14, 15], 
                      [16, 17, 18]], 

                     [[19, 20, 21], 
                      [22, 23, 24], 
                      [25, 26, 27]]])

print(array_3d)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [48]:
array_3d.ndim

3

In [49]:
array_3d.shape

(3, 3, 3)

In [50]:
b.shape

(3, 2)

In [51]:
a.shape

(3,)

In [52]:
array.shape

(3, 2)

In [53]:
A.shape

(3, 3)

In [54]:
print (A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
A.dtype

dtype('int32')

In [56]:
array_3d.dtype

dtype('int32')

In [57]:
b.dtype

dtype('int32')

In [58]:
a.dtype

dtype('int32')

In [59]:
array.dtype

dtype('int32')

In [65]:
e = np.array([4], dtype= 'int16')

In [66]:
print(e)

[4]


In [67]:
e.dtype

dtype('int16')

In [63]:
e.shape

(1,)

In [68]:
e.itemsize

2

In [69]:
e.size

1

In [70]:
b.itemsize

4

In [71]:
b.size

6

In [72]:
print(b)

[[1 2]
 [2 3]
 [1 3]]


In [73]:
b.size * b.itemsize

24

In [74]:
b.nbytes

24